theme: jekyll-theme-minimal
title: Naresh Thakur
logo: "/profile-pic.png?raw=true"
description: >
 <br>
 Passionate about technology, driven by intellectual curiosity!
  <br><br>
  <a href="https://www.linkedin.com/in/thinklikeacto/" target="_blank" rel="noreferrer"><img align="center" src="https://raw.githubusercontent.com/thinklikeacto/thinklikeacto/master/icons/linkedin.svg" alt="icon | LinkedIn" width="40px"/></a>&nbsp;&nbsp;
  <a href="https://thinklikeacto.medium.com/" target="_blank" rel="noreferrer"><img align="center" src="https://raw.githubusercontent.com/thinklikeacto/thinklikeacto/master/icons/medium.svg" alt="icon | Medium" width="40px"/></a>&nbsp;&nbsp;
  <a href="https://github.com/thinklikeacto" target="_blank" rel="noreferrer"><img align="center" src="https://raw.githubusercontent.com/thinklikeacto/thinklikeacto/master/icons/github.svg" alt="icon | GitHub" width="40px"/></a>&nbsp;&nbsp;
  <a href="https://leetcode.com/thinklikeacto/" target="_blank" rel="noreferrer"><img align="center" src="https://raw.githubusercontent.com/thinklikeacto/thinklikeacto/master/icons/leetcode-3521542-2944960.webp" alt="icon | Leetcode" width="40px"/></a>&nbsp;&nbsp;
  <a href="https://www.kaggle.com/thinklikeacto" target="_blank" rel="noreferrer"><img align="center" src="https://raw.githubusercontent.com/thinklikeacto/thinklikeacto/master/icons/kaggle-icon.png" alt="icon | Kaggle" width="40px"/></a>&nbsp;&nbsp;
  <a href="https://twitter.com/thinklikeacto" target="_blank" rel="noreferrer"><img align="center" src="https://raw.githubusercontent.com/thinklikeacto/thinklikeacto/master/icons/twitter-3-logo-svg-vector.svg" alt="icon | Twitter" width="40px"/></a>
  <br /><br />

